version: '1'

services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    restart: always
  api:
    build: ./api
    ports:
      - 5555:5000
    depends_on:
      - mysql
    restart: always
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=time_db
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
  adminer:
    image: adminer
    ports:
      - 8888:8080
    restart: always

volumes:
 mysql_data: